-- Repairs only the original development seed owner created by 002_seed_data.sql.
-- This does not alter production-created administrators or participant data.
-- No automatic password repair: provision or rotate a unique credential with
-- src/db/provision-owner.ts. Existing installations need explicit rotation.
