<script lang="ts">
  import { onMount } from 'svelte';
  import { api, ApiError } from '$lib/api/client.js';
  import { auth } from '$lib/stores/auth.store.js';
  import { Check, Clipboard, Clock3, Fingerprint, Link2, RefreshCw, ShieldCheck, Ticket, Users } from 'lucide-svelte';

  export let raffleId: string;

  type Engine = {
    raffle: { id: string; title: string; code: string; status: string; ticketsSold: number; ticketCap: number; drawCommitment: string | null; deadlineAt: string };
    participants: { id: string; fullName: string | null; phone: string; ticketCount: number; firstTicket: number; lastTicket: number }[];
    triggers: { id: string; attemptNumber: number; status: string; sentAt: string; expiresAt: string; clickedAt: string | null; phone: string }[];
    extensions: { id: string; previousDeadline: string; newDeadline: string; reason: string; extendedAt: string; ticketsSoldAtExtension: number }[];
    draws: { tier: number; prizeName: string; winningTicketCode: string; winnerName: string | null; drawnAt: string; finalSeedHash: string }[];
  };
  type TriggerResponse = { trigger: { link: string; delivery: 'sent' | 'demo' | 'failed'; expiresAt: string; selectedParticipant: { phone: string } | null; attemptNumber: number } };

  let engine: Engine | null = null;
  let loading = true;
  let generating = false;
  let error = '';
  let success = '';
  let generatedLink = '';
  let reason = 'Draw link generated by Platform Owner';

  async function load() {
    try {
      const response = await api.get<{ engine: Engine }>(`/admin/raffles/${raffleId}/engine`);
      engine = response.engine;
    } catch {
      error = 'Could not load the raffle engine.';
    } finally {
      loading = false;
    }
  }

  async function generate() {
    if (!engine || generating) return;
    generating = true;
    error = '';
    success = '';
    try {
      const response = await api.post<TriggerResponse>(`/admin/raffles/${raffleId}/draw-trigger`, { reason });
      generatedLink = response.trigger.link;
      success = response.trigger.delivery === 'sent'
        ? `Attempt ${response.trigger.attemptNumber} sent by SMS to ${response.trigger.selectedParticipant?.phone ?? 'the selected participant'}.`
        : `Attempt ${response.trigger.attemptNumber} created. Copy the link for this test environment.`;
      await load();
    } catch (cause) {
      error = cause instanceof ApiError ? 'The raffle must be locked and contain paid tickets before a link can be generated.' : 'Network error.';
    } finally {
      generating = false;
    }
  }

  async function copyLink() {
    if (!generatedLink) return;
    await navigator.clipboard.writeText(generatedLink);
    success = 'One-time link copied. It will not be shown again after this page closes.';
  }

  const ticketCode = (number: number) => `${engine?.raffle.code}-${String(number).padStart(5, '0')}`;
  onMount(load);
</script>

<section class="mt-5 rounded-card border border-border bg-card p-5 sm:p-6">
  <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-start">
    <div class="flex gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] bg-primary-bg text-primary"><Fingerprint size={19} /></span><div><p class="text-xs font-bold uppercase tracking-[0.14em] text-primary">Raffle engine</p><h2 class="mt-1 text-lg font-bold tracking-[-0.02em] text-ink">Fair draw control room</h2><p class="mt-1 max-w-xl text-xs leading-5 text-faint">One ticket is one chance. The selected community representative only starts the reveal and cannot select the winner.</p></div></div>
    <button type="button" on:click={load} class="admin-press flex h-9 items-center gap-2 self-start rounded-button border border-border px-3 text-xs font-bold text-muted"><RefreshCw size={13} /> Refresh</button>
  </div>

  {#if error}<p class="mt-4 rounded-button bg-danger-bg px-4 py-3 text-xs font-medium text-danger" role="alert">{error}</p>{/if}
  {#if success}<p class="mt-4 flex items-center gap-2 rounded-button bg-success-bg px-4 py-3 text-xs font-medium text-success"><Check size={14} /> {success}</p>{/if}

  {#if loading}
    <div class="mt-6 grid gap-3 sm:grid-cols-3">{#each Array(3) as _}<div class="h-24 animate-pulse rounded-button bg-bg"></div>{/each}</div>
  {:else if engine}
    <div class="mt-6 grid gap-3 sm:grid-cols-3">
      <div class="rounded-button bg-bg/65 p-4"><div class="flex items-center gap-2 text-faint"><Ticket size={14} /><span class="text-[11px] font-bold uppercase tracking-[0.1em]">Issued tickets</span></div><p class="mt-3 text-2xl font-bold tracking-[-0.03em] text-ink">{engine.raffle.ticketsSold}<span class="text-sm text-faint"> / {engine.raffle.ticketCap}</span></p><p class="mt-1 font-mono text-xs font-bold text-primary">{engine.raffle.code}</p></div>
      <div class="rounded-button bg-bg/65 p-4"><div class="flex items-center gap-2 text-faint"><Users size={14} /><span class="text-[11px] font-bold uppercase tracking-[0.1em]">Participants</span></div><p class="mt-3 text-2xl font-bold tracking-[-0.03em] text-ink">{engine.participants.length}</p><p class="mt-1 text-xs text-faint">Distinct verified accounts</p></div>
      <div class="rounded-button bg-bg/65 p-4"><div class="flex items-center gap-2 text-faint"><ShieldCheck size={14} /><span class="text-[11px] font-bold uppercase tracking-[0.1em]">Draw proof</span></div><p class="mt-3 text-sm font-bold text-ink">{engine.draws.length > 0 ? 'Finalized' : engine.raffle.drawCommitment ? 'Committed' : 'Legacy raffle'}</p><p class="mt-1 truncate font-mono text-[10px] text-faint">{engine.draws[0]?.finalSeedHash ?? engine.raffle.drawCommitment ?? 'No pre-commitment'}</p></div>
    </div>

    {#if engine.draws.length > 0}
      <div class="mt-5 grid gap-3 {engine.draws.length > 1 ? 'sm:grid-cols-3' : ''}">
        {#each engine.draws as draw (draw.tier)}
          <div class="flex flex-col gap-3 rounded-button border border-success/20 bg-success-bg p-5">
            <div class="flex items-center justify-between"><span class="rounded-full bg-success/15 px-2 py-0.5 text-[10px] font-black uppercase tracking-[0.08em] text-success">{draw.tier === 1 ? '1st place' : draw.tier === 2 ? '2nd place' : `${draw.tier}rd place`}</span><ShieldCheck size={18} class="text-success" /></div>
            <div><p class="truncate text-xs font-bold text-ink">{draw.prizeName}</p><p class="mt-1 text-xl font-black tracking-[-0.03em] text-ink">{draw.winningTicketCode}</p></div>
            <p class="text-xs text-muted">{draw.winnerName ?? 'Verified participant'} · {new Date(draw.drawnAt).toLocaleString()}</p>
          </div>
        {/each}
      </div>
    {:else if $auth.admin?.role === 'owner'}
      <div class="mt-5 grid gap-4 rounded-button border border-border bg-bg/35 p-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
        <label class="flex flex-col gap-2 text-xs font-bold text-ink">Generation reason<input bind:value={reason} maxlength="500" class="h-11 rounded-button border border-border bg-card px-3.5 text-sm font-medium text-ink focus:border-primary focus:outline-none" /></label>
        <button type="button" on:click={generate} disabled={generating || !['locked', 'awaiting_trigger'].includes(engine.raffle.status)} class="admin-press flex h-11 items-center justify-center gap-2 rounded-button bg-sidebar px-5 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Link2 size={15} /> {generating ? 'Selecting participant…' : engine.triggers.some((item) => item.status === 'pending') ? 'Replace draw link' : 'Generate draw link'}</button>
      </div>
      {#if generatedLink}<div class="mt-3 flex items-center gap-2 rounded-button border border-primary/20 bg-primary-bg p-2 pl-3"><p class="min-w-0 flex-1 truncate font-mono text-[11px] text-primary-dark">{generatedLink}</p><button type="button" on:click={copyLink} class="admin-press flex h-9 shrink-0 items-center gap-2 rounded-button bg-primary px-3 text-xs font-bold text-white"><Clipboard size={13} /> Copy once</button></div>{/if}
    {/if}

    <div class="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,.65fr)]">
      <div><div class="mb-3 flex items-center justify-between"><h3 class="text-sm font-bold text-ink">Participants and ticket ranges</h3><span class="text-[11px] text-faint">Maximum 5 each</span></div><div class="overflow-hidden rounded-button border border-border">{#if engine.participants.length === 0}<p class="p-5 text-xs text-faint">No paid tickets yet.</p>{:else}<div class="divide-y divide-border">{#each engine.participants as participant}<div class="grid grid-cols-[minmax(0,1fr)_auto] gap-3 px-4 py-3"><div class="min-w-0"><p class="truncate text-xs font-bold text-ink">{participant.fullName ?? 'Participant'}</p><p class="mt-0.5 text-[11px] text-faint">{participant.phone}</p></div><div class="text-right"><p class="text-xs font-bold text-primary">{participant.ticketCount} {participant.ticketCount === 1 ? 'ticket' : 'tickets'}</p><p class="mt-0.5 font-mono text-[10px] text-faint">{ticketCode(participant.firstTicket)}{participant.lastTicket !== participant.firstTicket ? ` – ${ticketCode(participant.lastTicket)}` : ''}</p></div></div>{/each}</div>{/if}</div></div>
      <div><h3 class="mb-3 text-sm font-bold text-ink">Draw-link history</h3><div class="space-y-2">{#if engine.triggers.length === 0}<div class="rounded-button border border-dashed border-border p-5 text-xs text-faint">No link generated yet.</div>{:else}{#each engine.triggers as trigger}<div class="rounded-button border border-border p-3"><div class="flex items-center justify-between"><p class="text-xs font-bold text-ink">Attempt {trigger.attemptNumber}</p><span class="rounded-full px-2 py-1 text-[10px] font-bold {trigger.status === 'pending' ? 'bg-warning-bg text-warning' : trigger.status === 'clicked' ? 'bg-success-bg text-success' : 'bg-bg text-faint'}">{trigger.status}</span></div><p class="mt-2 text-[11px] text-faint">Representative {trigger.phone}</p><p class="mt-1 flex items-center gap-1 text-[10px] text-faint"><Clock3 size={11} /> {new Date(trigger.expiresAt).toLocaleString()}</p></div>{/each}{/if}</div></div>
    </div>

    {#if engine.extensions.length > 0}<div class="mt-6"><h3 class="mb-3 text-sm font-bold text-ink">Extension history</h3><div class="space-y-2">{#each engine.extensions as extension}<div class="rounded-button bg-bg/55 px-4 py-3"><p class="text-xs font-bold text-ink">Extended to {new Date(extension.newDeadline).toLocaleString()}</p><p class="mt-1 text-[11px] leading-5 text-faint">{extension.reason} · {extension.ticketsSoldAtExtension} tickets sold at decision time</p></div>{/each}</div></div>{/if}
  {/if}
</section>
